---
title: "DUK_load_data"
author: "Ina Liao"
date: "2023-11-15"
output: pdf_document
---

```{r Install Packages}
#install.packages("lubridate")
#install.packages("ggplot2")
#install.packages("forecast")
#install.packages("here")
#install.packages("ggthemes")
#install.packages("openxlsx")
library(lubridate)
library(ggplot2)
library(forecast) 
library(here)
library(ggthemes)
library(openxlsx)
```

```{r Import Data, echo=TRUE, results='hide'}
raw_DUK<-read.csv(here('Data/Raw/load_DUK.csv'),stringsAsFactors = TRUE,skip=0,header=TRUE)
head(raw_DUK)
```
```{r Selected the needed data}
df_DUK<-raw_DUK[,c(5,8,9,10,11,45,46,47,48,49,50,51,52,53)]

#change the date format
df_DUK<-mutate(df_DUK,Local.Time=Local.time)
df_DUK<-separate(data=df_DUK,col=Local.time,into=c("Date","Time"),sep=" ") 
df_DUK$Date<-dmy(df_DUK$Date)
df_DUK$Time<-hms(df_DUK$Time)

#change the order
df_DUK<-df_DUK[,c(1:2,16,3:15)]

#rename column names 
colnames(df_DUK)[colnames(df_DUK)=="DF"]<-"Demand Forecast"
colnames(df_DUK)[colnames(df_DUK)=="D"]<-"Demand"
colnames(df_DUK)[colnames(df_DUK)=="NG"]<-"Net Generation"
colnames(df_DUK)[colnames(df_DUK)=="TI"]<-"Total Interchange"
```

```{r Export file}
write.csv(df_DUK, file = "Data/Processed Data/Processed_DUK.xlsx")
```