---
title: "weather_charlotte"
author: "Ina Liao"
date: "2023-11-15"
output: pdf_document
---

```{r Setup}
library(ggplot2)
library(tidyverse)
library(here)
library(dplyr)
library(shiny)
library(knitr)

here()
```

```{r Import Data}
df_2012<-read.csv(here('Data/Raw/weather/1044988_35.21_-80.86_2012.csv'),skip=2,stringsAsFactors = TRUE)
df_2013<-read.csv(here('Data/Raw/weather/1044988_35.21_-80.86_2013.csv'),skip=2,stringsAsFactors = TRUE)
df_2014<-read.csv(here('Data/Raw/weather/1044988_35.21_-80.86_2014.csv'),skip=2,stringsAsFactors = TRUE)
df_2015<-read.csv(here('Data/Raw/weather/1044988_35.21_-80.86_2015.csv'),skip=2,stringsAsFactors = TRUE)
df_2016<-read.csv(here('Data/Raw/weather/1044988_35.21_-80.86_2016.csv'),skip=2,stringsAsFactors = TRUE)
df_2017<-read.csv(here('Data/Raw/weather/1044988_35.21_-80.86_2017.csv'),skip=2,stringsAsFactors = TRUE)
df_2018<-read.csv(here('Data/Raw/weather/1044988_35.21_-80.86_2018.csv'),skip=2,stringsAsFactors = TRUE)
df_2019<-read.csv(here('Data/Raw/weather/1044988_35.21_-80.86_2019.csv'),skip=2,stringsAsFactors = TRUE)
df_2020<-read.csv(here('Data/Raw/weather/1044988_35.21_-80.86_2020.csv'),skip=2,stringsAsFactors = TRUE)
df_2021<-read.csv(here('Data/Raw/weather/1044988_35.21_-80.86_2021.csv'),skip=2,stringsAsFactors = TRUE)
df_2022<-read.csv(here('Data/Raw/weather/1044988_35.21_-80.86_2022.csv'),skip=2,stringsAsFactors = TRUE)

df_weather<-bind_rows(df_2012,df_2013,df_2014,df_2015,df_2016,df_2017,df_2018,df_2019,df_2020,df_2021,df_2022)
df_weather
```